# Generated by Django 5.2.5 on 2025-11-12 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField()),
                ('stage', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('smobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[6,9]\\d{9}')])),
            ],
        ),
    ]
