# Generated by Django 5.2.7 on 2025-11-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(unique=True)),
                ('loc', models.CharField(max_length=20)),
            ],
        ),
    ]
