# Generated by Django 5.2.7 on 2025-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='loc',
            field=models.TextField(max_length=20),
        ),
    ]
