# Generated by Django 5.2.7 on 2025-11-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dept_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='username',
        ),
    ]
