# Generated by Django 5.2.7 on 2025-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_dept_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='loc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Ename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Job',
            field=models.CharField(max_length=50),
        ),
    ]
