# Generated by Django 5.2.5 on 2025-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField()),
                ('stage', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('address', models.CharField()),
            ],
        ),
    ]
