# Generated by Django 5.2.5 on 2025-11-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_semail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semail',
            field=models.CharField(default='hai@gmail.com'),
        ),
    ]
