# Generated by Django 5.2.7 on 2025-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scname', models.CharField()),
                ('scloaction', models.CharField()),
                ('scprincipal', models.CharField()),
            ],
        ),
    ]
