# Generated by Django 5.2.5 on 2025-10-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Aid', models.IntegerField(primary_key=True, serialize=False)),
                ('Aname', models.CharField(max_length=100)),
                ('Amobile_no', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Bid', models.IntegerField(primary_key=True, serialize=False)),
                ('Bname', models.CharField(max_length=100)),
                ('Publish_date', models.DateField()),
                ('Aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
        ),
    ]
